Add window title
elementary/mail pull request #553
Opened 2021-03-14 09:28 UTC by JoseExposito

At the moment, the main window doesn't have a title. It is not a big deal since the title is not displayed anywhere in the UI.
However, once https://github.com/elementary/gala/issues/798 gets fixed, Gala will display "io.elementary.mail" as window title.

2021-03-14 16:19 UTC, cassidyjames commented
Window titles are also used in the Plank dock menu in the case of multiple windows, and generally should just be set no matter what in case they are used/displayed elsewhere. 👍

2021-03-14 16:21 UTC, cassidyjames requested changes
Reviewing on mobile, so apologies if I am missing something. But I think best practice is to set this in the object construction around line 69.

2021-03-15 17:06 UTC, JoseExposito commented
> Window titles are also used in the Plank dock menu in the case of multiple windows

Good point, @cassidyjames I didn't know they're displayed there. I made the changes you requested :smile:

2021-03-15 17:37 UTC, cassidyjames approved these changes

2021-03-15 17:37 UTC, merged