Basic functionality for Grouped Folders
elementary/mail pull request #564
Opened 2021-04-29 13:57 UTC by marbetschar

This PR eventually fixes https://github.com/elementary/mail/issues/449.

Right now it only adds a shared Inbox, however we may want to iterate on this a bit more to expand support to other well known folders if possible (such as Drafts, Outbox, Sent, Archive, Junk and Trash).

Please note the current implementation uses a hardcoded folder named "INBOX". While this seems to work for this particular folder, this does not seem to be a reliable approach for other well known folders. There is already a [open PR](https://github.com/elementary/mail/pull/545) which provides an improved folder detection mechanism - so that's probably a good starting point.

Also the current implementation does not support showing a badge with unread messages - this is also something we can improve upon.

![Screenshot from 2021-04-29 15-55-23](https://user-images.githubusercontent.com/392542/116562591-941f3000-a903-11eb-96c1-fea64da4b9f6.png)

2021-04-30 17:07 UTC, danrabbit commented
I can confirm that this works as expected! Can we add this to a header like "All Mailboxes" so it's a bit more clear what this is?

2021-05-03 06:25 UTC, marbetschar commented
@danrabbit added a "All Mailboxes" section header.

2021-05-03 10:03 UTC, hanaral commented
Would it be possible to add an 'all sent' button as well? iOS Mail has the ability to add/remove quite a few different unified section and I think it would be a good starting point to add the main 2

2021-05-03 17:24 UTC, danrabbit commented
@hanaral We usually prefer to have many smaller PRs than to try to do everything at once in a single branch. This makes code review faster and easier and helps with finding issues down the road if they occur

2021-05-03 21:45 UTC, marbetschar commented
@danrabbit / @hanaral I digged into this a bit more and added support for `INBOX`, `Drafts`, `Sent` and `Archive` folders. Please note, showing a badge with unread messages is still not supported yet.

2021-05-04 18:32 UTC, danrabbit requested changes
Inbox works here, but I'm getting a number of errors for the other mailboxes. I think it would be best to go back to just inbox in this branch and then do follow up branches for other other mailbox types

on launch I'm getting these:
```
** (io.elementary.mail:3157): CRITICAL **: 11:31:11.615: mail_grouped_folder_source_item_build_folder_full_name: assertion 'folder_uri != NULL' failed

** (io.elementary.mail:3157): WARNING **: 11:31:11.615: GroupedFolderSourceItem.vala:134: Grouped folder '(null)' not available for account 'daniel@elementary.io'

** (io.elementary.mail:3157): CRITICAL **: 11:31:11.619: mail_grouped_folder_source_item_build_folder_full_name: assertion 'folder_uri != NULL' failed

** (io.elementary.mail:3157): WARNING **: 11:31:11.619: GroupedFolderSourceItem.vala:134: Grouped folder '(null)' not available for account 'daniel.p.fore@gmail.com'

(io.elementary.mail:3157): camel-WARNING **: 11:31:13.398: CamelIMAPXStore::get_folder_info_sync() reported failure without setting its GError

** (io.elementary.mail:3157): WARNING **: 11:31:13.398: GroupedFolderSourceItem.vala:134: Grouped folder '%5bGmail%5d/Drafts' not available for account 'daniel@elementary.io'

(io.elementary.mail:3157): camel-WARNING **: 11:31:14.585: CamelIMAPXStore::get_folder_info_sync() reported failure without setting its GError

** (io.elementary.mail:3157): WARNING **: 11:31:14.585: GroupedFolderSourceItem.vala:134: Grouped folder '%5bGmail%5d/Drafts' not available for account 'daniel.p.fore@gmail.com'
```

when clicking sent:
```
g_variant_new_string: assertion 'string != NULL' failed
```

2021-05-04 18:36 UTC, danrabbit commented
Another small thing I'm noticing is that when we first open Mail, it restores the selected folder for example if you select Inbox under one of your accounts. But if the last selected folder was one of these grouped folders, it does not restore on startup

2021-05-05 09:07 UTC, marbetschar commented
- Reverted to INBOX only
- Automatically select INBOX on app start
- Merged latest master

2021-05-06 17:50 UTC, danrabbit reviewed
This works as expected for me, nice job! Only two very small code comments

2021-05-06 17:50 UTC, danrabbit commented on src/ConversationList/ConversationListBox.vala
> +        foreach (var selected_row in selected_rows) {
should this still be:
```suggestion
        foreach (unowned var selected_row in selected_rows) {
```

2021-05-06 17:50 UTC, danrabbit commented on src/ConversationList/ConversationListBox.vala
> +        foreach (var selected_row in selected_rows) {
unowned again probably?
```suggestion
        foreach (unowned var selected_row in selected_rows) {
```

2021-05-06 21:56 UTC, marbetschar commented
@danrabbit made the fixes as suggested. Everything still works on my end, so I guess we are good. Still not 100% sure about when to use `unowned` though :)

2021-05-07 18:44 UTC, danrabbit approved these changes
LFG :rocket:

2021-05-07 18:44 UTC, merged