Filter Conversations
elementary/mail pull request #678
Opened 2021-09-01 19:13 UTC by marbetschar

This PR fixes https://github.com/elementary/mail/issues/10 and https://github.com/elementary/mail/issues/236 by adding the functionality to filter for unread and/or starred conversations in the currently selected folder (see video below).

Things which still needs to be addressed:

- [ ] We probably want to change the icon. Some kind of funnel would be nice - but I was unable to find an appropriate icon.
- [ ] Querying fails with `Invalid types in AND` when combined with a search term - no clue why.

https://user-images.githubusercontent.com/392542/131730087-88ac1991-bf5d-4441-b6a8-71a0c065034d.mp4

2021-09-02 02:58 UTC, marbetschar commented
Managed to get rid of all s-expression warnings. However, the search still does not work as expected when combined with unread/important flags. @tintou is this a bug in upstream - or what am I missing here?

2021-09-08 19:34 UTC, tintou commented on src/ConversationList/ConversationListBox.vala
> +                current_search_expressions += """(not "read")""";
Looking at evolution, it should be:
```suggestion
                current_search_expressions += """(not (system-flag "Seen"))""";
```

2021-09-08 19:35 UTC, tintou commented on src/ConversationList/ConversationListBox.vala
> +                current_search_expressions += """(not (not "important"))""";
```suggestion
                current_search_expressions += """(not (system-flag "Flagged"))""";
```

2021-09-09 07:50 UTC, marbetschar commented
Thank you @tintou - this did the trick! It works now as expected on my end. However, this is painfully slow to test and would greatly benefit from the changes introduced in https://github.com/elementary/mail/pull/676.

So to whomever is gonna reviewing this, its probably less painfull to review the other PR first :)

2021-09-17 08:10 UTC, tintou approved these changes
Works!

2021-09-21 21:58 UTC, danrabbit requested changes
I'm not sure switches make the most sense here since we're choosing which items to include as part of a list and not turning a specific feature on or off.

One way we could do this is to change the switch labels to something like "Hide read messages" and "Hide unstarred messages". That would make them actions instead of objects, and then you wouldn't need the explainer text either

It would probably be nice to create some kind of filter icon. I would bet that there might have already been one made for LibreOffice that we could use

2021-09-21 21:58 UTC, danrabbit commented on src/HeaderBar.vala
> +        };
We can really reduce the padding here quite a bit
```suggestion
        var filter_menu_popover_grid = new Gtk.Grid () {
            margin_bottom = 3,
            margin_top = 3,
            orientation = Gtk.Orientation.VERTICAL
        };
```

2021-09-21 21:58 UTC, danrabbit commented on src/HeaderBar.vala
> +            can_focus = false,
We don't want to prevent buttons from being able to gain focus. This would make it inaccessible with the keyboard
```suggestion
```

2021-09-21 21:58 UTC, danrabbit commented on src/HeaderBar.vala
> +        search_entry.width_request = end_position - start_position - filter_button.get_allocated_width () - 6;
I guess this should use the end margin of the filter button so we know where this number comes from
```suggestion
        search_entry.width_request = end_position - start_position - filter_button.get_allocated_width () - filter_button.margin_end;
```

2021-09-22 05:49 UTC, marbetschar commented
@danrabbit definitely better - thank you very much for adding the required changes to the PR as well!! IMHO this is good to go, what do you think?

2021-09-22 16:14 UTC, danrabbit approved these changes
Let's ship it!

2021-09-22 16:14 UTC, merged