Subclass Gtk.Box instead of Gtk.ListBox in Mail.MessageListBox
elementary/mail pull request #845
Opened 2023-03-30 15:44 UTC by leolost2605

This is being done in preparation for a gtk4 port, as `Gtk.ListBox` will be final in gtk4. Also move the `HeaderBar` from its own class here.

- [x] Change class
- [x] Move its scrolled window to `MessageListBox` from `MainWindow`
- [x] Move headerbar
- [x] Rename to MessageList

2023-03-31 11:39 UTC, leolost2605 commented
Sorry, wanted to request review from the team, how do i do that? 😳

2023-03-31 12:24 UTC, lenemter commented
@leolost2605 Only organization members can request review from the team

2023-03-31 12:39 UTC, lenemter commented on src/MessageList/MessageListItem.vala
Why `parent_message_list_box` was introduced here? Is accessing parent somehow broken in GTK 4 version?

2023-03-31 21:03 UTC, leolost2605 commented on src/MessageList/MessageListItem.vala
> +        parent_message_list_box.add_inline_composer.begin (composer_type, this);
Oh nice, didn't know about that, thank you!

2023-04-04 18:08 UTC, danirabbit commented
@leolost2605 regarding the question in the PR description, I agree that moving the headerbar here and renaming this class to "MessageList" makes sense :+1:

2023-04-04 18:10 UTC, danirabbit commented on src/MessageList/MessageListBox.vala
> +            spacing: 0
I think spacing is 0 by default so I'm not sure you need to set this explicitly

2023-04-07 18:02 UTC, danirabbit requested changes
One small inline suggestion. Also don't forget to update po/POTFILES :)

2023-04-07 19:17 UTC, danirabbit approved these changes

2023-04-07 19:20 UTC, merged